//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int inventory_id { get; set; }
        public string inventory_item { get; set; }
        public string inventory_desc { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> worker_id { get; set; }
    }
}
